# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

try:
    from . import fire_service_pb2 as proto_dot_fire__service__pb2
except ImportError:
    import fire_service_pb2 as proto_dot_fire__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/fire_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FireQueryServiceStub(object):
    """Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Query = channel.unary_stream(
                '/fire_service.FireQueryService/Query',
                request_serializer=proto_dot_fire__service__pb2.QueryRequest.SerializeToString,
                response_deserializer=proto_dot_fire__service__pb2.QueryResponseChunk.FromString,
                _registered_method=True)
        self.CancelRequest = channel.unary_unary(
                '/fire_service.FireQueryService/CancelRequest',
                request_serializer=proto_dot_fire__service__pb2.StatusRequest.SerializeToString,
                response_deserializer=proto_dot_fire__service__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/fire_service.FireQueryService/GetStatus',
                request_serializer=proto_dot_fire__service__pb2.StatusRequest.SerializeToString,
                response_deserializer=proto_dot_fire__service__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.InternalQuery = channel.unary_unary(
                '/fire_service.FireQueryService/InternalQuery',
                request_serializer=proto_dot_fire__service__pb2.InternalQueryRequest.SerializeToString,
                response_deserializer=proto_dot_fire__service__pb2.InternalQueryResponse.FromString,
                _registered_method=True)
        self.Notify = channel.unary_unary(
                '/fire_service.FireQueryService/Notify',
                request_serializer=proto_dot_fire__service__pb2.InternalQueryRequest.SerializeToString,
                response_deserializer=proto_dot_fire__service__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/fire_service.FireQueryService/HealthCheck',
                request_serializer=proto_dot_fire__service__pb2.HealthRequest.SerializeToString,
                response_deserializer=proto_dot_fire__service__pb2.HealthResponse.FromString,
                _registered_method=True)


class FireQueryServiceServicer(object):
    """Service definition
    """

    def Query(self, request, context):
        """Client -> Gateway (Process A): Submit a query
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelRequest(self, request, context):
        """Client -> Gateway: Cancel a request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Client -> Gateway: Check request status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InternalQuery(self, request, context):
        """Internal: Process to Process communication
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Notify(self, request, context):
        """Internal: One-way notification (optional)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FireQueryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Query': grpc.unary_stream_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=proto_dot_fire__service__pb2.QueryRequest.FromString,
                    response_serializer=proto_dot_fire__service__pb2.QueryResponseChunk.SerializeToString,
            ),
            'CancelRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelRequest,
                    request_deserializer=proto_dot_fire__service__pb2.StatusRequest.FromString,
                    response_serializer=proto_dot_fire__service__pb2.StatusResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=proto_dot_fire__service__pb2.StatusRequest.FromString,
                    response_serializer=proto_dot_fire__service__pb2.StatusResponse.SerializeToString,
            ),
            'InternalQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.InternalQuery,
                    request_deserializer=proto_dot_fire__service__pb2.InternalQueryRequest.FromString,
                    response_serializer=proto_dot_fire__service__pb2.InternalQueryResponse.SerializeToString,
            ),
            'Notify': grpc.unary_unary_rpc_method_handler(
                    servicer.Notify,
                    request_deserializer=proto_dot_fire__service__pb2.InternalQueryRequest.FromString,
                    response_serializer=proto_dot_fire__service__pb2.StatusResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=proto_dot_fire__service__pb2.HealthRequest.FromString,
                    response_serializer=proto_dot_fire__service__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fire_service.FireQueryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fire_service.FireQueryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FireQueryService(object):
    """Service definition
    """

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/fire_service.FireQueryService/Query',
            proto_dot_fire__service__pb2.QueryRequest.SerializeToString,
            proto_dot_fire__service__pb2.QueryResponseChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fire_service.FireQueryService/CancelRequest',
            proto_dot_fire__service__pb2.StatusRequest.SerializeToString,
            proto_dot_fire__service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fire_service.FireQueryService/GetStatus',
            proto_dot_fire__service__pb2.StatusRequest.SerializeToString,
            proto_dot_fire__service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InternalQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fire_service.FireQueryService/InternalQuery',
            proto_dot_fire__service__pb2.InternalQueryRequest.SerializeToString,
            proto_dot_fire__service__pb2.InternalQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Notify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fire_service.FireQueryService/Notify',
            proto_dot_fire__service__pb2.InternalQueryRequest.SerializeToString,
            proto_dot_fire__service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fire_service.FireQueryService/HealthCheck',
            proto_dot_fire__service__pb2.HealthRequest.SerializeToString,
            proto_dot_fire__service__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
